services:
  postgres:
    container_name: postgres-sql-tt
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: task_tracker
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - tt-network
    restart: unless-stopped
networks:
  tt-network:
    driver: bridge

volumes:
  postgres:
    driver: local